=== api-evangelist/cloudwatch/json-schema/cloudwatch-put-composite-alarm-input-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "PutCompositeAlarmInput",
  "type": "object",
  "properties": {
    "AlarmName": {
      "type": "string",
      "description": "The name for the composite alarm."
    },
    "AlarmDescription": {
      "type": "string",
      "description": "The description for the composite alarm."
    },
    "ActionsEnabled": {
      "type": "boolean",
      "description": "Indicates whether actions should be executed during any changes to the alarm state."
    },
    "AlarmActions": {
      "type": "array",
      "description": "The actions to execute when this alarm transitions to the ALARM state."
    },
    "AlarmRule": {
      "type": "string",
      "description": "An expression that specifies which other alarms are to be evaluated to determine this composite alarm's state."
    },
    "InsufficientDataActions": {
      "type": "array",
      "description": "The actions to execute when this alarm transitions to the INSUFFICIENT_DATA state."
    },
    "OKActions": {
      "type": "array",
      "description": "The actions to execute when this alarm transitions to the OK state."
    },
    "Tags": {
      "type": "array",
      "description": "A list of key-value pairs to associate with the composite alarm."
    },
    "ActionsSuppressor": {
      "type": "string",
      "description": "Actions will be suppressed if the suppressor alarm is in the ALARM state."
    },
    "ActionsSuppressorWaitPeriod": {
      "type": "integer",
      "description": "The maximum time in seconds that the composite alarm waits for the suppressor to go into ALARM state."
    },
    "ActionsSuppressorExtensionPeriod": {
      "type": "integer",
      "description": "The maximum time in seconds that the composite alarm waits after the suppressor leaves the ALARM state."
    }
  }
}

=== api-evangelist/cloudwatch/examples/cloudwatch-put-composite-alarm-input-example.json
{
  "AlarmName": "example_value",
  "AlarmDescription": "example_value",
  "ActionsEnabled": true,
  "AlarmActions": [],
  "AlarmRule": "example_value",
  "InsufficientDataActions": [],
  "OKActions": [],
  "Tags": [],
  "ActionsSuppressor": "example_value",
  "ActionsSuppressorWaitPeriod": 10,
  "ActionsSuppressorExtensionPeriod": 10
}
